# server port
server:
  port: 8080

web:
  url: http://news.sina.com.cn
  commentUrl: http://comment5.news.sina.com.cn/page/info?version=1&format=json&
  agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Mobile Safari/537.36

logging:
  config: classpath:logback-boot.xml

taskExecutor:
  corePoolSize: 100
  maxPoolSize: 200
  queueCapacity: 500
  threadNamePrefix: Executor-


